/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthCheckRouteImport } from './routes/auth-check'
import { Route as IndexRouteImport } from './routes/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCheckRoute = AuthCheckRouteImport.update({
  id: '/auth-check',
  path: '/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-check': typeof AuthCheckRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-check': typeof AuthCheckRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-check': typeof AuthCheckRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth-check' | '/callback' | '/dashboard' | '/signin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth-check' | '/callback' | '/dashboard' | '/signin'
  id: '__root__' | '/' | '/auth-check' | '/callback' | '/dashboard' | '/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCheckRoute: typeof AuthCheckRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-check': {
      id: '/auth-check'
      path: '/auth-check'
      fullPath: '/auth-check'
      preLoaderRoute: typeof AuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCheckRoute: AuthCheckRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
